spring.application.name=backend

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/bookfair_db
spring.datasource.username=postgres
spring.datasource.password=Converter
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
# Optional: You can actually remove the line below; Hibernate 6+ detects this automatically
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false


# --- NEW EMAIL CONFIGURATION (SSL - PORT 465) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.protocol=smtps
spring.mail.username=bookfair.system@gmail.com
spring.mail.password=hyba gwtv oevb gudk

# SSL Properties
spring.mail.properties.mail.transport.protocol=smtps
spring.mail.properties.mail.smtps.auth=true
spring.mail.properties.mail.smtps.starttls.enable=true
spring.mail.properties.mail.smtps.ssl.trust=smtp.gmail.com

# TIMEOUTS (60 Seconds)
spring.mail.properties.mail.smtps.timeout=60000
spring.mail.properties.mail.smtps.connectiontimeout=60000
spring.mail.properties.mail.smtps.writetimeout=60000

spring.mail.debug=true

# JWT Configuration (legacy local auth)
app.jwtSecret=MySuperSecretKeyForTheBookFairProjectWhichShouldBeVeryLong12345!
app.jwtExpirationMs= 3000000

# --- Auth0 OAuth2 Resource Server ---
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-v7ho3u6edp4k7e5u.us.auth0.com/
auth0.audience=https://stallreservation.com/api